### ISSUE TITLE
What is the purpose of `memcpy` field in `Config` struct?

### ISSUE THREAD

**Issue by vita-dounai** [rust-osdev/cargo-xbuild#102]
The declaration is located at https://github.com/rust-osdev/cargo-xbuild/blob/f6ce1e5da41ad68951657a87abd2e034de611eb1/src/config.rs#L15

**Comment by phil-opp** [comment]
See <https://github.com/rust-osdev/cargo-xbuild#configuration>:

> The memcpy flag defines whether the mem feature of the compiler_builtins crate should be activated. Turning this flag off allows to specify own versions of the memcpy, memset etc. functions.
