### ISSUE TITLE
cargo-xbuild doesn't build with older nightlies

### ISSUE THREAD

**Issue by vamanea** [rust-osdev/cargo-xbuild#106]
My project uses rust nightly 2021-03-23 and since some time I can't build cargo-xbuild anymore, on account of this error:

```
error[E0658]: use of unstable library feature 'btree_retain'
   --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.83/src/map.rs:286:18
    |
286 |         self.map.retain(f);
    |                  ^^^^^^
    |
    = note: see issue #79025 <https://github.com/rust-lang/rust/issues/79025> for more information
    = help: add `#![feature(btree_retain)]` to the crate attributes to enable
```
With older serde_json(1.0.59) it builds fine.

 The [linked issue](https://github.com/rust-lang/rust/issues/79025) was fixed in 2021 Apr 14 nightlies, so updating the toolchain to that fixed my issue. The other solution is to request a specific version of serde_json in Cargo.toml.

I'm not sure which is the better fix, but I think at least updating the README to indicate the latest supported toolchain is needed.

**Comment by phil-opp** [comment]
Why do you need to install `cargo-xbuild` using the pinned nightly? Installing it through `cargo +stable install cargo-xbuild` should work in your case.

**Comment by vamanea** [comment]
Right, that didn't occur to me, no idea why. Sorry for the noise.
