### ISSUE TITLE
TARGET in build.rs is invalid

### ISSUE THREAD

**Issue by berkus** [rust-osdev/cargo-xbuild#19]
When using a full path to json file as cargo-xbuild `--target` argument, the resulting TARGET is not a triple but instead a full file path. I believe it should be a triple.

According to [cargo book](https://doc.rust-lang.org/cargo/reference/environment-variables.html):

> TARGET - the target triple that is being compiled for. Native code should be compiled for this triple. 

What I'm getting:

```
λ cargo xbuild --target=targets/aarch64-vesper-metta.json
   Compiling vesper v1.0.0 (/path/to/vesper)
error: failed to run custom build command for `vesper v1.0.0 (/path/to/vesper)`
process didn't exit successfully: `/path/to/vesper/target/debug/build/vesper-6432e1d623b2c988/build-script-build` (exit code: 101)
--- stderr
Target /path/to/vesper/targets/aarch64-vesper-metta.json
thread 'main' panicked at 'TARGET env variable is not set to one of supported values', build.rs:43:9
```

The line `Target /path/to/vesper/targets/aarch64-vesper-metta.json` is output by build.rs from the TARGET env var.

**Comment by phil-opp** [comment]
Seems like the cargo documentation is not specific enough or out of date. A target triple in rust can be either a triple string or a path to a JSON file: https://github.com/rust-lang/rust/blob/653da4fd006c97625247acd7e076d0782cdc149b/src/librustc_target/spec/mod.rs#L1275-L1278

**Comment by berkus** [comment]
Hmm, ok, still very inconvenient because my build.rs only need to look at the TRIPLE regardless of actual json file path.

Can this be added? Maybe even to cargo? (As TARGET_TRIPLE for example)

**Comment by berkus** [comment]
Probably it makes more sense to match on `(CARGO_CFG_TARGET_ARCH, CARGO_CFG_TARGET_OS, CARGO_CFG_TARGET_FAMILY)` triple instead.

**Comment by berkus** [comment]
I used direct match on the env vars and it worked excellently!

**Comment by phil-opp** [comment]
Cool!
