### ISSUE TITLE
Tag 0.4.3 release?

### ISSUE THREAD

**Issue by alex** [rust-osdev/cargo-xbuild#2]
I see 0.4.3 was uploaded to crates.io, but it doesn't seem to be tagged at: https://github.com/rust-osdev/cargo-xbuild/tags

(Possibly a forgotten `git push --tags`? Definitely not guessing from experience here... :-))

**Comment by phil-opp** [comment]
Yeah, it seems like I forgot it. Thanks for the hint!

Should be fixed now.
