### ISSUE TITLE
Document XBUILD_SYSROOT_PATH in README.md

### ISSUE THREAD

**Issue by Nils-TUD** [rust-osdev/cargo-xbuild#35]
The README currently only describes that the sysroot path can be modified in the Cargo.toml. Unfortunately, this approach doesn't work if a workspace is used, because this results in many packages in the metadata and ``cargo-xbuild`` always searches for its options in the first package.

It just took me several hours to figure out that this is the problem and that there actually is an alternative: the ``XBUILD_SYSROOT_PATH`` environment variable. Please document that in the README ;)

**Comment by phil-opp** [comment]
Thanks for reporting! I added the missing documentation in 994b5e7.
