### ISSUE TITLE
How to build the documentation using cargo xbuild? 

### ISSUE THREAD

**Issue by gnzlbg** [rust-osdev/cargo-xbuild#38]
I am using `xargo doc` to build documentation. What's the corresponding `cargo-xbuild` command for that ?

**Comment by phil-opp** [comment]
It doesn't exist yet since nobody needed it so far. But it should be relatively simple to add by creating a new binary in src/bin. Do you want to create a pull request?

**Comment by Nils-TUD** [comment]
As an intermediate solution, you can also use the normal ``cargo doc`` for it:

        export RUSTFLAGS="--sysroot <sysroot>"
        export RUSTDOCFLAGS=$RUSTFLAGS
        cargo doc --target <target>

**Comment by gnzlbg** [comment]
Thanks, I'll stick to `xargo` for the time being - not sure when I'll have time to create a PR.

**Comment by phil-opp** [comment]
@gnzlbg Sure! Let's keep this issue open, maybe someone has time to implement it.

**Comment by gnzlbg** [comment]
@phil-opp wow thank you! I'll see if I can get libc using this instead of `xargo`. The work of migrating to `cargo-xbuild` is happening as part of: https://github.com/rust-lang/libc/pull/1376

**Comment by phil-opp** [comment]
Thank @Aehmlo, I only pushed the merge button :D.

> I'll see if I can get libc using this instead of xargo. The work of migrating to cargo-xbuild is happening as part of: rust-lang/libc#1376

Oh wow, I didn't expect that. Let me know if you have any problems!

**Comment by gnzlbg** [comment]
Thank you @Aehmlo ! 

> Let me know if you have any problems!

All green - it just worked.

**Comment by phil-opp** [comment]
Perfect, great to hear that!
