### ISSUE TITLE
xc, xb, xr, xt

### ISSUE THREAD

**Issue by Aehmlo** [rust-osdev/cargo-xbuild#41]
Cargo has four built-in command aliases<sup>1</sup>: `c` for `check`, `b` for `build`, `r` for `run`, and `t` for `test`. It would be consistent and useful during development for `cargo-xbuild` to provide `x`-prefixed versions of these (`xc` for `xcheck`, `xb` for `xbuild`, `xr` for `xrun`, and `xt` for `xtest`). I propose staying in sync with Cargo and only adding short aliases that exist there (e.g. *not* adding `xd` → `xdoc`).

I know I can do this locally, but I'd like to have it provided by `cargo-xbuild`. I'd be happy to help out with the implementation work.

<sup>1</sup>See the bottom of the [Cargo configuration key reference](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys) (yes, it's a bit of an odd place for this documentation to reside, but oh well).

**Comment by phil-opp** [comment]
Sounds good to me!
