### ISSUE TITLE
Using as a library

### ISSUE THREAD

**Issue by ascjones** [rust-osdev/cargo-xbuild#58]
It would be really useful for me to be able to use this as a library, since it would avoid requiring the user to install `cargo_xbuild` as a separate step. I'm just playing with it now, and it seems I can just make a few bits public to get what I want: https://github.com/rust-osdev/cargo-xbuild/compare/master...ascjones:pub-build-fn.

Let me know whether this is a sensible idea and I can continue down this path and create a PR with these changes.

**Comment by phil-opp** [comment]
I see no problems with making `build` available in the library. So feel free to open a PR for this!
