### ISSUE TITLE
Can we support `xfix`?

### ISSUE THREAD

**Issue by tjhu** [rust-osdev/cargo-xbuild#63]
Can we support the command [`cargo fix`](https://doc.rust-lang.org/cargo/commands/cargo-fix.html) in tool? Thanks!

**Comment by phil-opp** [comment]
Sure! I'd be happy to merge a PR for this.

See https://github.com/rust-osdev/cargo-xbuild/pull/12 for an example on how to add a new command.

**Comment by phil-opp** [comment]
Implemented in https://github.com/rust-osdev/cargo-xbuild/pull/64.
