### ISSUE TITLE
Option to not remove temporary files

### ISSUE THREAD

**Issue by deliciouslytyped** [rust-osdev/cargo-xbuild#66]
Can you please add an option not to delete all the temporary build files? I ran into a rustc segfault and I can't debug it.

**Comment by deliciouslytyped** [comment]
Well xargo has this https://github.com/japaric/xargo/blob/cd0a4f41292e524d08544c050672ab04c2af5da7/src/sysroot.rs#L83

**Comment by phil-opp** [comment]
Sounds useful! I opened #67 to implement this.
